### ISSUE TITLE
amqp1 issue

### ISSUE THREAD

**Issue by paramite** [infrawatch/apputils#27]
Building collectd-sensubility with qpid-proton-c version higher than 0.34.0 makes sensubility to fail during sending second message with:

panic: cannot marshal string: overflow: not enough space to encode

goroutine 8 [running]:
github.com/apache/qpid-proton/go/pkg/amqp.marshal({0x68c3e0?, 0xc00012a410?}, 0x0?)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/amqp/marshal.go:293 +0xa47
github.com/apache/qpid-proton/go/pkg/amqp.putData({0x68c3e0, 0xc00012a410}, 0x44c0e5?)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/amqp/message.go:508 +0x50
github.com/apache/qpid-proton/go/pkg/amqp.(*message).put(0xc000154000, 0x200000003?)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/amqp/message.go:560 +0x2b8
github.com/apache/qpid-proton/go/pkg/amqp.(*MessageCodec).Encode(0x0?, {0x758e20?, 0xc000154000?}, {0x0, 0x0, 0x0})
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/amqp/message.go:380 +0x9f
github.com/apache/qpid-proton/go/pkg/electron.(*sender).send(0xc0002e0000, 0xc00011a630)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/sender.go:197 +0x12b
github.com/apache/qpid-proton/go/pkg/electron.(*sender).trySend(0xc0002e0000)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/sender.go:187 +0x25
github.com/apache/qpid-proton/go/pkg/electron.(*sender).startSend(...)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/sender.go:179
github.com/apache/qpid-proton/go/pkg/electron.(*sender).SendAsyncTimeout.func1()
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/sender.go:230 +0xc5
github.com/apache/qpid-proton/go/pkg/proton.(*Engine).Run(0xc0000f2360)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/proton/engine.go:376 +0x14f
github.com/apache/qpid-proton/go/pkg/electron.(*connection).run(0xc0001880f0)
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/connection.go:241 +0x45
created by github.com/apache/qpid-proton/go/pkg/electron.NewConnection
        /root/go/pkg/mod/github.com/apache/qpid-proton@v0.0.0-20210222174104-6353ad99c23d/go/pkg/electron/connection.go:224 +0x570

**Comment by paramite** [comment]
We need to either pin on 0.34.0 or figure out what's the issue with the current amqp1 connector code.

**Comment by paramite** [comment]
Fixed in PR #29.
